RaidDistribution
Almtr/joycontrol-plugins pull request #2
Opened 2020-08-10 13:36 UTC by Zobio

レイドポケモン自動配布プログラムを追加しました。
ゲームを開いたときに、配布をしたいポケモンの巣の前にいるようにした状態で、
$ sudo joycontrol-pluginloader -r <Switch Bluetooth Mac address> plugins/pokemon-swsh/RaidDistribution.py <Link Code>
と打ってください。
レイドバトルの待機時間は約１分にしています。

2020-08-10 14:05 UTC, Zobio commented
$ sudo joycontrol-pluginloader -r plugins/pokemon-swsh/RaidDistribution.py <Link Code>
の間違いです、すみません

2020-08-10 14:08 UTC, Zobio commented
すみません、
$ sudo joycontrol-pluginloader -r (MACアドレス) plugins/pokemon-swsh/RaidDistribution.py (リンクコード8桁)
の間違いです

2020-08-10 14:50 UTC, Almtr commented
インデントは、スペース4つに統一してください。

2020-08-10 14:52 UTC, Almtr commented on pokemon-swsh/RaidDistribution.py
> +            await self.wait(0.5)
press_time_sec のデフォルト値は、0.1秒です。
0.1秒間ボタンを押したい場合は、必要ありませんので、削除してください。

2020-08-10 15:07 UTC, Almtr requested changes
いくつか修正項目を書きましたので、修正後再度リクエストをお願いします。

2020-08-10 15:07 UTC, Almtr commented on pokemon-swsh/RaidDistribution.py
> +        linkCode = self.options[0]
オプションを指定していない場合のエラー処理を追加してください。

```python
if self.options is None:
    raise JoycontrolPluginError('Plugin option is not set. Please use "--plugin-options <link_code>".')

linkCode = self.options[0]
```

JoycontrolPluginError を使用する場合、import にJoycontrolPluginError を追加してください。

```python
from JoycontrolPlugin import JoycontrolPlugin, JoycontrolPluginError
```

2020-08-10 15:07 UTC, Almtr commented on pokemon-swsh/RaidDistribution.py
> +            await self.wait(0.5)
press_time_sec のデフォルト値は、0.1 秒です。
0.1秒間ボタンを押したい場合は、必要ありませんので削除してください。

2020-08-10 15:07 UTC, Almtr commented on pokemon-swsh/RaidDistribution.py
> +            await self.wait(0.5)
また、インデント幅がスペース1つになっているので、スペース4つに統一してください。

2020-08-12 16:23 UTC, Almtr requested changes
RaidDistribution と RaidDistributionFromBackup が混在しています。どちらか1つに統一してください。
また、他にも修正点を書いておりますので、お手数ですが修正をお願いします。

2020-08-12 16:23 UTC, Almtr commented on pokemon-swsh/RaidDistributionFromBackup.py
> +            raise JoycontrolPluginError('Plugin option is not set. Please use "--plugin-options <link_code>".')
エラー処理が適切に行えていません。
この実装では、オプション未指定の場合に以下のようなエラーが出ます。
```sh
'NoneType' object is not subscriptable
```

self.options が None かどうか判定した後に、self.options[0] を参照するように実装する必要があります。

2020-08-12 16:23 UTC, Almtr commented on pokemon-swsh/RaidDistributionFromBackup.py
> +        num = 0
num は、45行目の for文内でのみ使用されています。
ここで初期化する必要はありません。

2020-08-12 16:23 UTC, Almtr commented on pokemon-swsh/RaidDistributionFromBackup.py
> +                        await self.wait(0.5)
1. 番号を押した後のカーソル位置をゼロに移動させる処理について
   - 下ボタン長押しにすればすべて共通の実装にできます。  
   - ボタンを押す前にカーソルを移動すれば、``num != 7`` の確認が必要なくなります。

1. linkCode に数字以外が指定された場合のエラー処理を追加してください。
   ここに実装するか、12行目辺りにまとめて行うといいと思います。

以下、実装例になります。

```python
for num in range(8):
    # Move to zero to reset the cursor position.
    await self.button_push('down', press_time_sec=0.6)

    # Move to target number
    if linkCode[num] == '0':
        pass # don't move
    elif linkCode[num] == '1':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('left')
        await self.wait(0.5)
    elif linkCode[num] == '2':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
    elif linkCode[num] == '3':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('right')
        await self.wait(0.5)
    elif linkCode[num] == '4':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('left')
        await self.wait(0.5)
    elif linkCode[num] == '5':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
    elif linkCode[num] == '6':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('right')
        await self.wait(0.5)
    elif linkCode[num] == '7':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('left')
        await self.wait(0.5)
    elif linkCode[num] == '8':
        await self.button_push('up')
        await self.wait(0.5)
    elif linkCode[num] == '9':
        await self.button_push('up')
        await self.wait(0.5)
        await self.button_push('right')
        await self.wait(0.5)
    else:
        raise ValueError('Invalid link code.')

    # push number
    await self.button_push('a')
    await self.wait(0.5)
```

2020-08-12 16:31 UTC, Zobio commented on pokemon-swsh/RaidDistributionFromBackup.py
> +                        await self.wait(0.5)
ありがとうございます。
最初下ボタン長押で統一していたのですが、7、8、9などの0(初期位置に)近い位置にあった場合無駄な時間が生まれてしまうため場合わけしました。
しかしプログラムの見通しが悪くなるので修正すべきでしょうか...?

2020-08-12 16:35 UTC, Zobio commented
RaidDistribution.py→セーブデータからロードしてレイド配布
RaidDistributionFromBackup.py→バックアップデータからロードしてレイド配布
となっているので、できれば2つともマージしていただきたいです。

2020-08-12 16:38 UTC, Almtr commented
なるほど、承知しました。
修正項目は共通だと思うので、それぞれ同様に修正をお願いします。

2020-08-12 17:31 UTC, Almtr commented on pokemon-swsh/RaidDistributionFromBackup.py
> +                        await self.wait(0.5)
ここは、一長一短な気がしますね。

123456が多く使われる場合、長押しの方が速く移動できます。
また、0.6秒以内の長押しであれば、789の場合でも同等の速度で移動できます。
ただし、0の場合は、0.6秒遅くなってしまいます。

プログラムの見通しが悪くなってしまいますが、1秒もあれば、0にまで移動できるはずので、長押しと組み合わせて実装するというのでもいいかもしれません。

2020-08-12 19:45 UTC, Zobio commented
３つ変更を行いました。
・名称をを変更しました。
セーブデータからレイド配布→DistributeRaidFromSaveData.py
バックからレイド配布→DistributeRaidFromBackup.py
・ご指摘いただいたところを修正しました。
・LinkCode入力のアルゴリズムを最適化させました。
いちいち０に戻らずに入力できるように場合分けしました。

2020-08-12 20:19 UTC, Zobio commented
３つ変更を行いました。
・名称をを変更しました。
セーブデータからレイド配布→DistributeRaidFromSaveData.py
バックからレイド配布→DistributeRaidFromBackup.py
・ご指摘いただいたところを修正しました。
・LinkCode入力のアルゴリズムを最適化させました。
いちいち０に戻らずに入力できるように場合分けしました。
せっかく書き方を教えていただいたのに申し訳ないです。

2020-08-12 20:35 UTC, Zobio commented
以下が概要です。
最初の1周目は1が開始点なので、2こめのそれぞれの値(0-9)に対応した動きをする。
2周目以降は最初に変更前(num - 1)か変更後(bum)が0であるか確認し、0の場合はそれぞれに対応した動きをする。
それ以外の場合は、変更前と変更後の数字の差と変更前の位置から場合わけし、対応した位置にカーソルがいくようにする。

2020-08-15 00:50 UTC, Almtr requested changes
ChangeRaidPokemon.py は、別のプラグインですので、一度削除して別のブランチを分けて Pull Request を送ってください。
また、キーパットの入力に関してアルゴリズムの見直しをご検討ください。

2020-08-15 00:50 UTC, Almtr commented on pokemon-swsh/DistributeRaidFromBackup.py
> +                await self.wait(0.5)
無駄な処理が多く、プログラムの見通しが悪いので、もう少しアルゴリズムを見直してください。
また、linkCode の1つ目に数字以外が指定された場合のエラー処理が抜けています。
ファイルが増えてきたので、DistributionRaid のようなディレクトリを作成してまとめてもいいと思います。

以下、実装例になります。

- Keypad.py
  - キーパッドの最短経路探索を行う。
  - 別のファイルに分割すると、DistributeRaidFromBackup でも使いまわせます。

```python
import itertools

class Keypad:
    def __init__(self):
        self.keypad = [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
            [-1,0,-1],
        ]

    def __num2pos(self, num: int):
        max_x = len(self.keypad[0])
        max_y = len(self.keypad)
        for x, y in itertools.product(range(max_x), range(max_y)):
            if self.keypad[y][x] == num:
                return {'x':x, 'y':y}
        return None

    def shortest_path(self, current_num: int, target_num: int):
        current_pos = self.__num2pos(current_num)
        target_pos = self.__num2pos(target_num)
        max_x = len(self.keypad[0])
        max_y = len(self.keypad)

        path = []
        while True:
            x = current_pos['x']
            y = current_pos['y']
            diff_x = target_pos['x'] - current_pos['x']
            diff_y = target_pos['y'] - current_pos['y']

            if diff_x == diff_y == 0:
                break

            if   diff_x > 0 and 0 <= x+1 < max_x and self.keypad[y][x+1] != -1:
                path.append('right')
                current_pos['x'] += 1
            elif diff_x < 0 and 0 <= x-1 < max_x and self.keypad[y][x-1] != -1:
                path.append('left')
                current_pos['x'] -= 1
            elif diff_y > 0 and 0 <= y+1 < max_y and self.keypad[y+1][x] != -1:
                path.append('down')
                current_pos['y'] += 1
            elif diff_y < 0 and 0 <= y-1 < max_y and self.keypad[y-1][x] != -1:
                path.append('up')
                current_pos['y'] -= 1
        return path
```

- DistributeRaidFromSaveData.py
  - push_linkcode で求めた最短経路通りにボタンを押す。
  - ``not linkCode.isdecimal()`` でロード直後に ``linkCode`` が正しいかどうかチェックする。

```python
import logging
from JoycontrolPlugin import JoycontrolPlugin, JoycontrolPluginError
import os
import sys

sys.path.append(os.path.abspath(os.path.dirname(__file__)))
import Keypad

logger = logging.getLogger(__name__)

class DistributeRaidFromSaveData(JoycontrolPlugin):
    async def push_linkcode(self, linkcode):
        keypad = Keypad.Keypad()
        current_num = 1 # init position
        for num in linkcode:
            target_num = int(num)
            path = keypad.shortest_path(current_num, target_num))
            for button in path:
                await self.button_push(button) # Move to target number
                await self.wait(0.5)
            await self.button_push('a') # Push number
            await self.wait(0.5)
            current_num = target_num

    async def distribute_raid_from_save_data(self):
        # 省略

        if not linkCode.isdecimal():
            raise ValueError('Invalid link code.')

        count = 0
        while True:
            # 省略
            await self.push_linkcode(linkCode)
            # 省略
```

2020-08-20 13:04 UTC, merged