ChangeRaidPokemonブランチを作り、ChangeRaidPokemon.pyをmasterブランチから移しました。
Almtr/joycontrol-plugins pull request #8
Opened 2020-08-15 18:11 UTC by Zobio

2020-08-15 18:19 UTC, Zobio commented
レイドバトルのポケモンを目当てのものが出るまで無限にシャッフルするプログラムです。
巣穴の前に**Ｗをすでに回収し終えている状態で**セーブします。その後プログラムを起動してください。
また、この際日付が（大の月の場合は）２９、３０、３１日以外になっているようにしてください。
３日進めた後、変更されたポケモンが出てきます。目当てのポケモンが出たら、ここでプログラムを強制終了させてください。
そうではなかった場合、一定時間経過後にソフトが終了し、日付を３日戻し、またはじめから繰り返すようになっています。

2020-08-16 09:24 UTC, Almtr requested changes
1点修正項目を書きましたので、修正をお願いします。

2020-08-16 09:24 UTC, Almtr commented on pokemon-swsh/ChangeRaidPokemon.py
> +                await self.wait(0.1)
ここはどういう意図の処理なのでしょうか。
4匹目のポケモンであることをユーザに知らせるための処理という理解で合っていますでしょうか。

2020-08-16 09:24 UTC, Almtr commented on pokemon-swsh/ChangeRaidPokemon.py
> +                await self.wait(0.8)
日付変更バグを使用して、レイドに出現するポケモンの変更を行っているようですので、
ChangeRaidPokemon.py も TimeSkipGlitch 以下に移動させてください。
また、日付変更は、ほぼ同様の実装がありますので、TimeSkipGlitch/TimeSkipBasePlugin.py と統合してください。

2020-08-16 09:25 UTC, Zobio commented on pokemon-swsh/ChangeRaidPokemon.py
> +                await self.wait(0.1)
すみませんそのことを書くのを忘れていました、その通りです

2020-08-16 09:27 UTC, Zobio commented on pokemon-swsh/ChangeRaidPokemon.py
> +                await self.wait(0.8)
上記の内容をTimeSkipBasePlugin.pyに追加する、ということで大丈夫でしょうか？

2020-08-16 15:02 UTC, Almtr commented on pokemon-swsh/ChangeRaidPokemon.py
> +                await self.wait(0.8)
はい、change_daysのようなメソッドを追加して、日付を変更できるように処理をまとめてください。
引数で進める日数を指定できるようにすれば、1つにまとめられると思います。

2020-08-16 15:35 UTC, Almtr commented on pokemon-swsh/ChangeRaidPokemon.py
> +                await self.wait(0.8)
全然テストしていないので動くか分かりませんが、実装例はこんな感じです。

- TimeSkipBasePlugin.py

```python
import logging
from JoycontrolPlugin import JoycontrolPlugin

logger = logging.getLogger(__name__)

class TimeSkipBasePlugin(JoycontrolPlugin):
    async def open_date_and_time_settings(self):
        # Open the "Home"
        await self.button_push('home')
        await self.wait(0.8)

        # Open the "Home > System Settings"
        await self.button_push('down')
        await self.wait(0.1)
        await self.button_push('right', press_time_sec=0.8)
        await self.wait(0.1)
        await self.button_push('left')
        await self.wait(0.1)
        await self.button_push('a')
        await self.wait(0.8)

        # Open the "Home > System Settings > System"
        await self.button_push('down', press_time_sec=1.5)
        await self.wait(0.3)
        await self.button_push('a')
        await self.wait(0.3)

        # Open the "Home > System Settings > System > Date and Time"
        await self.button_push('down', press_time_sec=0.6)
        await self.wait(0.1)
        await self.button_push('a')
        await self.wait(0.5)

        # Open the "Home > System Settings > System > Date and Time > Date and Time"
        await self.button_push('down', press_time_sec=0.7)
        await self.wait(0.1)
        await self.button_push('a')
        await self.wait(0.3)
    
    async def restart_game(self):
        await self.button_push('home')
        await self.wait(1.0)
        await self.button_push('a')
        await self.wait(0.5)

    async def change_year(self):
        await self.open_date_and_time_settings()

        # Set next year
        await self.button_push('up')
        await self.wait(0.1)
        await self.button_push('right', press_time_sec=1.0)
        await self.wait(0.1)
        await self.button_push('a')
        await self.wait(0.1)

        await self.button_push('a')
        await self.wait(0.1)

        # Set previous year
        await self.button_push('left', press_time_sec=1.0)
        await self.wait(0.1)
        await self.button_push('down')
        await self.wait(0.1)
        await self.button_push('right', press_time_sec=1.0)
        await self.wait(0.1)
        await self.button_push('a')
        await self.wait(0.1)

        await self.restart_game()
    

    async def change_days(days):
        await self.open_date_and_time_settings()

        await self.button_push('a')
        await self.wait(0.1)
        await self.button_push('a')
        await self.wait(0.1)

        direction = 'up'
        if days < 0:
            direction = 'down'
        
        for _ in range(abs(days)):
            await self.button_push(direction)
            await self.wait(0.1)

        await self.button_push('right', press_time_sec=0.5)
        await self.wait(0.1)
        await self.button_push('a')
        await self.wait(0.1)

        await self.restart_game()
```

- ChangeRaidPokemon.py

```python
import logging
import os
import sys

sys.path.append(os.path.abspath(os.path.dirname(__file__)))
from TimeSkipBasePlugin import TimeSkipBasePlugin

logger = logging.getLogger(__name__)

class ChangeRaidPokemon(TimeSkipBasePlugin):
    async def run(self):
        logger.info('Change Raid Pokemon Plugin loaded!')

        lap = 0
        while True:
            for i in range(3):
                if i == 0:
                    await self.button_push('a')
                    await self.wait(0.6)
                    await self.button_push('a')
                    await self.wait(1.8)
                else:
                    await self.button_push('a')
                    await self.wait(0.6)
                    await self.button_push('a')
                    await self.wait(0.3)
                    await self.button_push('a')
                    await self.wait(0.3)
                    await self.button_push('a')
                    await self.wait(0.6)
                    await self.button_push('a')
                    await self.wait(1.8)

                await self.change_days(1)

                await self.button_push('b')
                await self.wait(0.8)
                await self.button_push('a')
                await self.wait(3.8)
                
            await self.button_push('a')
            await self.wait(0.6)
            await self.button_push('a')
            await self.wait(0.4)
            await self.button_push('a')
            await self.wait(0.4)    
            for _ in range(10):
                await self.button_push('down')
                await self.wait(0.1)
                await self.button_push('up')
                await self.wait(0.1)
            await self.wait(2)
            await self.button_push('home')
            await self.wait(1)
            await self.button_push('x')
            await self.wait(0.5)
            await self.button_push('a')
            await self.wait(4)

            await self.change_days(-3)

            await self.button_push('a')
            await self.wait(0.5)
            await self.button_push('a')
            await self.wait(20)
            await self.button_push('a')
            await self.wait(10)        
            lap += 1
            logger.info(str(lap) + 'cycle finished.')
```

2020-08-16 17:09 UTC, Zobio commented
すみません、こちらのコメントを確認しておらず、Pull Requestを送った後に初めて確認しています。申し訳ないです。
ChangeRaiPokemon.pyはalmtrさんとおおよそ同じなのですが、TimeSkipBasePlugin.pyはかなり内容が異なっているので、コメントしていただいているような内容に変更した方がよろしいでしょうか?

2020-08-16 21:55 UTC, Almtr commented
ほぼ同じ処理ですので、気にしなくて大丈夫です。他に修正項目はないので、動作確認が取れたらマージします。

2020-08-17 02:46 UTC, Zobio commented
承知しました。
よろしくお願いします。

2020-08-17 19:39 UTC, merged